<?php
return [
    'name'                      => 'Backend',
    'logo'                      => '<b>Back</b> End',
    'logo-mini'                 => '<b>BE</b>',
    'bootstrap'                 => base_path('bootstrap/backend.php'),
    'route'                     => [
        'prefix'     => env('ADMIN_ROUTE_PREFIX', 'backend'),
        'namespace'  => 'App\\Http\\Controllers\\Backend',
        'middleware' => ['web', 'backend'],
    ],
    'directory'                 => app_path('Http/Controllers/Backend'),
    'title'                     => 'Backend',
    'https'                     => env('ADMIN_HTTPS', false),
    'auth'                      => [
        'controller'        => App\Http\Controllers\Backend\AuthController::class,
        'guard'             => 'backend',
        'guards'            => [
            'backend' => [
                'driver'   => 'session',
                'provider' => 'backend',
            ],
        ],
        'providers'         => [
            'backend' => [
                'driver' => 'eloquent',
                'model'  => Base\Admin\Auth\Database\Administrator::class,
            ],
        ],
        'remember'          => true,
        'redirect_to'       => 'auth/login',
        'throttle_logins'   => true,
        'throttle_attempts' => 5,
        'throttle_timeout'  => 900,
        'excepts'           => [
            'auth/login',
            'auth/logout',
        ],
    ],
    'upload'                    => [
        'disk'      => 'backend',
        'directory' => [
            'image' => 'images',
            'file'  => 'files',
        ],
    ],
    'database'                  => [
        'connection'             => '',
        'users_table'            => 'admin_users',
        'users_model'            => Base\Admin\Auth\Database\Administrator::class,
        'roles_table'            => 'admin_roles',
        'roles_model'            => Base\Admin\Auth\Database\Role::class,
        'permissions_table'      => 'admin_permissions',
        'permissions_model'      => Base\Admin\Auth\Database\Permission::class,
        'menu_table'             => 'admin_menu',
        'menu_model'             => Base\Admin\Auth\Database\Menu::class,
        'operation_log_table'    => 'admin_operation_log',
        'user_permissions_table' => 'admin_user_permissions',
        'role_users_table'       => 'admin_role_users',
        'role_permissions_table' => 'admin_role_permissions',
        'role_menu_table'        => 'admin_role_menu',
    ],
    'operation_log'             => [
        'enable'          => true,
        'allowed_methods' => ['GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'CONNECT', 'OPTIONS', 'TRACE', 'PATCH'],
        'except'          => [
            env('ADMIN_ROUTE_PREFIX', 'backend') . '/auth/logs*',
        ],
        'filter_input'    => [
            'token'             => '*****-filtered-out-*****',
            'password'          => '*****-filtered-out-*****',
            'password_remember' => '*****-filtered-out-*****',
        ],
    ],
    'check_route_permission'    => true,
    'check_menu_roles'          => true,
    'default_avatar'            => '/vendor/bupind/base-admin/gfx/user.svg',
    'map_provider'              => 'openstreetmaps',
    'skin'                      => '',
    'layout'                    => ['sidebar-mini', 'sidebar-collapse'],
    'login_background_image'    => '',
    'show_version'              => true,
    'show_environment'          => true,
    'menu_bind_permission'      => true,
    'enable_default_breadcrumb' => true,
    'minify_assets'             => [
        'excepts' => [],
    ],
    'enable_menu_search'        => false,
    'enable_user_panel'         => false,
    'top_alert'                 => '',
    'grid_action_class'         => \Base\Admin\Grid\Displayers\Actions\Actions::class,
];
